---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 13.80.177.112 #40.114.197.248
      ansible_port: 22
      ansible_ssh_user: jenkins
    #app01:
    #  ansible_host: app01
    #app02:
    #  ansible_host: app02
  vars:
    ansible_python_interpreter: /usr/bin/python3

